# Generated by Django 6.0 on 2025-12-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mfdate',
        ),
    ]
