# Generated by Django 6.0 on 2025-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_products_mfdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
